### PR TITLE
Implemented disconnect for Windows.

### PR DESCRIPTION
**Pull request by obermillerk**

### CODE REVIEW

**Comment by obermillerk** [comment]
I tested this against my Windows 10 machine using your test code and it worked no problem.

**Comment by thibaultfriedrich** [comment]
Ok thx a lot. I never took the time to create this function for windows. I am grateful for your help. I can only trust you but it is enough for me ;).

**Comment by obermillerk** [comment]
I'm looking into current connections atm as well

**Comment by thibaultfriedrich** [comment]
I will push it on npm during the next week.

**Pull request merged**
